FROM python:3.11
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y libgl1-mesa-glx && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host=files.pythonhosted.org
# Instale as bibliotecas necessárias

RUN pip install --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host=files.pythonhosted.org opencv-python
RUN pip install --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host=files.pythonhosted.org flask
RUN pip install --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host=files.pythonhosted.org pybase64
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org SQLAlchemy
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org Flask-SQLAlchemy

COPY ./ /usr/src/app
ENV FLASK_APP=app
CMD ["python3", "app.py"]